### PR TITLE
User Authentication # 001

### PR DESCRIPTION
**Pull request by PrinceNiyonshuti**
#### What does this PR do?

- Implements user Authentication

#### Description of Task to be completed? 

**A user should be able**

**Register**

- create a new account by providing a username, email, password
- validate the username, email, password

**Login**

- login by providing username and password 
- if the username and password provided are valid then after generating the JWT token 
- if the username and password provided are not valid gets **Not Authorized** error

**Check User Profile**

- user can check the profile by passing the token to **Bearer-token** if it's valid he/she the profile
- user can check the profile by passing the token to **Bearer-token** if it's not valid he/she get **Not Authorized** cant see the profile

#### How should this be manually tested?

- Clone the repo

- checkout to branch ``auth_functionality``

- Run `yarn install to install modules

- Run `yarn start:dev` to start the development server

**In your API testing tool (postman recommended) call API** 
- `method: Post` `localhost:5000/api/auth/signup` to create new account 
- `method: Post` `localhost:5000/api/auth/login` to login the user
- `method: Get` `localhost:5000/api/auth/user-profile` to check the profile of authenticated user

#### Any background context you want to provide?

- Note that you should send the request with username, email, and password to create a new account
- **request body** 
 ``
  {
    "username":"test username",
    "email":"username@gmail.com",
    "password":"password"
  }
  ``
- Note that you should send the request with an email and password to login into your account
- **request body** 
 ``
  {
    "email":"username@gmail.com",
    "password":"password"
  }
  ``
- Note that you should send the request with a valid auth bearer token to check your user profile

#### What are the relevant Pivotal Tracker/Trello stories?

- [link to Trello Board](https://trello.com/c/ssK8y9Qh/23-user-authentication-001)

#### Screenshots (if appropriate)
N/A 

#### Questions:

N/A

### CODE REVIEW

**Review by PatrickNiyogitare28 — CHANGES_REQUESTED** [review]
add this `.env` file into `.gitgnore` . Practically it is not pushed to github

**Review by PatrickNiyogitare28 — APPROVED** [review]
But you did an expected work

**Comment by PrinceNiyonshuti** [comment]
> But you did an expected work

thanks and I have fixed it in the last commit

**Review by PatrickNiyogitare28 — APPROVED** [review]
Now we're good to go

**Comment by shemalucien** [comment]
Good work prince keep it up

**Pull request merged**
